// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrxYYctYxsXdtsH3xuvSFk68CmxNPSew',
    appId: '1:674019005957:web:c66ac51b0f67a859762e6c',
    messagingSenderId: '674019005957',
    projectId: 'spotify-app-e0d60',
    authDomain: 'spotify-app-e0d60.firebaseapp.com',
    storageBucket: 'spotify-app-e0d60.appspot.com',
    measurementId: 'G-2F25GS4C6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAax-rbHgcbE9BuZewFNudSKkN4S2RUyfM',
    appId: '1:674019005957:android:40f05fc7b2a5a31f762e6c',
    messagingSenderId: '674019005957',
    projectId: 'spotify-app-e0d60',
    storageBucket: 'spotify-app-e0d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJLjP5Af__0CtkH-p75-qM4brvF9MhiHg',
    appId: '1:674019005957:ios:9e5f59899df4579e762e6c',
    messagingSenderId: '674019005957',
    projectId: 'spotify-app-e0d60',
    storageBucket: 'spotify-app-e0d60.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJLjP5Af__0CtkH-p75-qM4brvF9MhiHg',
    appId: '1:674019005957:ios:9e5f59899df4579e762e6c',
    messagingSenderId: '674019005957',
    projectId: 'spotify-app-e0d60',
    storageBucket: 'spotify-app-e0d60.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMrxYYctYxsXdtsH3xuvSFk68CmxNPSew',
    appId: '1:674019005957:web:aefeb9efebf3e71e762e6c',
    messagingSenderId: '674019005957',
    projectId: 'spotify-app-e0d60',
    authDomain: 'spotify-app-e0d60.firebaseapp.com',
    storageBucket: 'spotify-app-e0d60.appspot.com',
    measurementId: 'G-S9SBE6SMG1',
  );
}
